[package]
name = "blog-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
blog-client = { path = "../blog-client" }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }